version: '3.8'

services:
  mysql:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: blood_donation_mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blood_donation_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blood_donation_network

volumes:
  mysql_data:

networks:
  blood_donation_network:
    driver: bridge 